version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    # env_file:
    #   - .env
    environment:
      - DB_HOST=postgres
      - DB_NAME=fastapi
      - DB_USER=postgres
      - DB_PASSWORD=mankindjnr
      - DB_PORT=5432
      - SECRET_KEY="b7ffab7e88ff8ec8e6c258944ec6677542bd7a16431ef01c0b78aaea77b26e04"
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mankindjnr
      - POSTGRES_DB=fastapi
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: